title: Octavio Landa | Análisis e Integridad de la Información
description: Portafolio Profesional de Ciencia de Datos y Auditoría de Sistemas.
theme: jekyll-theme-midnight
google_analytics: 
show_downloads: false